module Symbols exposing (getSymbol, allSymbols)

import Dict exposing (Dict)


{-| Look up a symbol name for a memory address
-}
getSymbol : Int -> Maybe String
getSymbol addr =
    Dict.get addr symbolTable


{-| All defined symbols as a list
-}
allSymbols : List ( Int, String )
allSymbols =
    Dict.toList symbolTable


{-| C64 memory map symbols
-}
symbolTable : Dict Int String
symbolTable =
    Dict.fromList
        [ -- Zero Page - Common locations
          ( 0x01, "CPU_PORT" )
        , ( 0x03, "ADRAY1" )
        , ( 0x05, "ADRAY2" )
        , ( 0x14, "TXTPTR" )
        , ( 0x2B, "TXTTAB" )
        , ( 0x2D, "VARTAB" )
        , ( 0x31, "STRTAB" )
        , ( 0x33, "FRETOP" )
        , ( 0x37, "MEMSIZ" )
        , ( 0x39, "CURLIN" )
        , ( 0x3D, "FORPNT" )
        , ( 0x61, "FAC1" )
        , ( 0x69, "FAC2" )
        , ( 0x7A, "CHRGET" )
        , ( 0x8B, "CHRGOT" )
        , ( 0x90, "STATUS" )
        , ( 0x91, "STKEY" )
        , ( 0x93, "VERCK" )
        , ( 0x94, "C3PO" )
        , ( 0x97, "XSAV" )
        , ( 0x9D, "MSGFLG" )
        , ( 0xA0, "JIFFY_CLOCK" )
        , ( 0xA3, "BESSION" )
        , ( 0xA4, "TLNIDX" )
        , ( 0xB2, "EAL" )
        , ( 0xB7, "FNLEN" )
        , ( 0xBA, "FA" )
        , ( 0xBB, "FNADR" )
        , ( 0xC5, "LSTX" )
        , ( 0xC6, "NDX" )
        , ( 0xCB, "SFDX" )
        , ( 0xCC, "BLNSW" )
        , ( 0xCE, "GDBLN" )
        , ( 0xD3, "PNTR" )
        , ( 0xD6, "LNMX" )

        -- Screen RAM
        , ( 0x0400, "SCREEN_RAM" )

        -- BASIC ROM entry points
        , ( 0xA000, "BASIC_COLD_START" )
        , ( 0xA00C, "BASIC_WARM_START" )
        , ( 0xA533, "BASIC_PRINT" )
        , ( 0xA560, "BASIC_PRINT_INT" )
        , ( 0xA8F8, "BASIC_GETBYT" )
        , ( 0xAD9E, "BASIC_FRMNUM" )
        , ( 0xAE83, "BASIC_GETADR" )
        , ( 0xB7F7, "BASIC_MOVMF" )
        , ( 0xBDCD, "BASIC_PRINTSTR" )

        -- KERNAL ROM entry points
        , ( 0xE500, "CINT" )
        , ( 0xE518, "IOINIT_SCREEN" )
        , ( 0xE544, "CLEAR_SCREEN" )
        , ( 0xE566, "HOME" )
        , ( 0xE5A0, "SET_CURSOR" )
        , ( 0xE8EA, "SCROLL_UP" )
        , ( 0xEA31, "IRQ_HANDLER" )
        , ( 0xEA87, "SCNKEY" )
        , ( 0xF49E, "LOAD_RAM" )
        , ( 0xF5ED, "SAVE" )
        , ( 0xF69B, "SETHDR" )
        , ( 0xFD15, "RESTOR" )
        , ( 0xFD50, "RAMTAS" )
        , ( 0xFDA3, "IOINIT" )
        , ( 0xFDF9, "SETMSG" )
        , ( 0xFE25, "NMI_HANDLER" )
        , ( 0xFF43, "IRQ_ENTRY" )
        , ( 0xFF48, "NMI_ENTRY" )

        -- KERNAL jump table
        , ( 0xFF81, "CINT_JUMP" )
        , ( 0xFF84, "IOINIT_JUMP" )
        , ( 0xFF87, "RAMTAS_JUMP" )
        , ( 0xFF8A, "RESTOR_JUMP" )
        , ( 0xFF8D, "VECTOR" )
        , ( 0xFF90, "SETMSG_JUMP" )
        , ( 0xFF93, "SECOND" )
        , ( 0xFF96, "TKSA" )
        , ( 0xFF99, "MEMTOP" )
        , ( 0xFF9C, "MEMBOT" )
        , ( 0xFF9F, "SCNKEY_JUMP" )
        , ( 0xFFA2, "SETTMO" )
        , ( 0xFFA5, "ACPTR" )
        , ( 0xFFA8, "CIOUT" )
        , ( 0xFFAB, "UNTLK" )
        , ( 0xFFAE, "UNLSN" )
        , ( 0xFFB1, "LISTEN" )
        , ( 0xFFB4, "TALK" )
        , ( 0xFFB7, "READST" )
        , ( 0xFFBA, "SETLFS" )
        , ( 0xFFBD, "SETNAM" )
        , ( 0xFFC0, "OPEN" )
        , ( 0xFFC3, "CLOSE" )
        , ( 0xFFC6, "CHKIN" )
        , ( 0xFFC9, "CHKOUT" )
        , ( 0xFFCC, "CLRCHN" )
        , ( 0xFFCF, "CHRIN" )
        , ( 0xFFD2, "CHROUT" )
        , ( 0xFFD5, "LOAD" )
        , ( 0xFFD8, "SAVE" )
        , ( 0xFFDB, "SETTIM" )
        , ( 0xFFDE, "RDTIM" )
        , ( 0xFFE1, "STOP" )
        , ( 0xFFE4, "GETIN" )
        , ( 0xFFE7, "CLALL" )
        , ( 0xFFEA, "UDTIM" )
        , ( 0xFFED, "SCREEN" )
        , ( 0xFFF0, "PLOT" )
        , ( 0xFFF3, "IOBASE" )

        -- Hardware vectors
        , ( 0xFFFA, "NMI_VECTOR" )
        , ( 0xFFFC, "RESET_VECTOR" )
        , ( 0xFFFE, "IRQ_VECTOR" )

        -- VIC-II Registers
        , ( 0xD000, "VIC_SPRITE0_X" )
        , ( 0xD001, "VIC_SPRITE0_Y" )
        , ( 0xD002, "VIC_SPRITE1_X" )
        , ( 0xD003, "VIC_SPRITE1_Y" )
        , ( 0xD004, "VIC_SPRITE2_X" )
        , ( 0xD005, "VIC_SPRITE2_Y" )
        , ( 0xD006, "VIC_SPRITE3_X" )
        , ( 0xD007, "VIC_SPRITE3_Y" )
        , ( 0xD008, "VIC_SPRITE4_X" )
        , ( 0xD009, "VIC_SPRITE4_Y" )
        , ( 0xD00A, "VIC_SPRITE5_X" )
        , ( 0xD00B, "VIC_SPRITE5_Y" )
        , ( 0xD00C, "VIC_SPRITE6_X" )
        , ( 0xD00D, "VIC_SPRITE6_Y" )
        , ( 0xD00E, "VIC_SPRITE7_X" )
        , ( 0xD00F, "VIC_SPRITE7_Y" )
        , ( 0xD010, "VIC_SPRITES_X_MSB" )
        , ( 0xD011, "VIC_CONTROL1" )
        , ( 0xD012, "VIC_RASTER" )
        , ( 0xD013, "VIC_LIGHT_PEN_X" )
        , ( 0xD014, "VIC_LIGHT_PEN_Y" )
        , ( 0xD015, "VIC_SPRITE_ENABLE" )
        , ( 0xD016, "VIC_CONTROL2" )
        , ( 0xD017, "VIC_SPRITE_EXPAND_Y" )
        , ( 0xD018, "VIC_MEMORY_SETUP" )
        , ( 0xD019, "VIC_IRQ_STATUS" )
        , ( 0xD01A, "VIC_IRQ_ENABLE" )
        , ( 0xD01B, "VIC_SPRITE_PRIORITY" )
        , ( 0xD01C, "VIC_SPRITE_MULTICOLOR" )
        , ( 0xD01D, "VIC_SPRITE_EXPAND_X" )
        , ( 0xD01E, "VIC_SPRITE_COLLISION" )
        , ( 0xD01F, "VIC_SPRITE_BG_COLLISION" )
        , ( 0xD020, "VIC_BORDER_COLOR" )
        , ( 0xD021, "VIC_BG_COLOR0" )
        , ( 0xD022, "VIC_BG_COLOR1" )
        , ( 0xD023, "VIC_BG_COLOR2" )
        , ( 0xD024, "VIC_BG_COLOR3" )
        , ( 0xD025, "VIC_SPRITE_MC0" )
        , ( 0xD026, "VIC_SPRITE_MC1" )
        , ( 0xD027, "VIC_SPRITE0_COLOR" )
        , ( 0xD028, "VIC_SPRITE1_COLOR" )
        , ( 0xD029, "VIC_SPRITE2_COLOR" )
        , ( 0xD02A, "VIC_SPRITE3_COLOR" )
        , ( 0xD02B, "VIC_SPRITE4_COLOR" )
        , ( 0xD02C, "VIC_SPRITE5_COLOR" )
        , ( 0xD02D, "VIC_SPRITE6_COLOR" )
        , ( 0xD02E, "VIC_SPRITE7_COLOR" )

        -- SID Registers
        , ( 0xD400, "SID_V1_FREQ_LO" )
        , ( 0xD401, "SID_V1_FREQ_HI" )
        , ( 0xD402, "SID_V1_PW_LO" )
        , ( 0xD403, "SID_V1_PW_HI" )
        , ( 0xD404, "SID_V1_CONTROL" )
        , ( 0xD405, "SID_V1_ATTACK_DECAY" )
        , ( 0xD406, "SID_V1_SUSTAIN_RELEASE" )
        , ( 0xD407, "SID_V2_FREQ_LO" )
        , ( 0xD408, "SID_V2_FREQ_HI" )
        , ( 0xD409, "SID_V2_PW_LO" )
        , ( 0xD40A, "SID_V2_PW_HI" )
        , ( 0xD40B, "SID_V2_CONTROL" )
        , ( 0xD40C, "SID_V2_ATTACK_DECAY" )
        , ( 0xD40D, "SID_V2_SUSTAIN_RELEASE" )
        , ( 0xD40E, "SID_V3_FREQ_LO" )
        , ( 0xD40F, "SID_V3_FREQ_HI" )
        , ( 0xD410, "SID_V3_PW_LO" )
        , ( 0xD411, "SID_V3_PW_HI" )
        , ( 0xD412, "SID_V3_CONTROL" )
        , ( 0xD413, "SID_V3_ATTACK_DECAY" )
        , ( 0xD414, "SID_V3_SUSTAIN_RELEASE" )
        , ( 0xD415, "SID_FILTER_FREQ_LO" )
        , ( 0xD416, "SID_FILTER_FREQ_HI" )
        , ( 0xD417, "SID_FILTER_RESONANCE" )
        , ( 0xD418, "SID_VOLUME_FILTER" )
        , ( 0xD419, "SID_POT_X" )
        , ( 0xD41A, "SID_POT_Y" )
        , ( 0xD41B, "SID_OSC3_RANDOM" )
        , ( 0xD41C, "SID_ENV3" )

        -- CIA 1
        , ( 0xDC00, "CIA1_PORT_A" )
        , ( 0xDC01, "CIA1_PORT_B" )
        , ( 0xDC02, "CIA1_DDR_A" )
        , ( 0xDC03, "CIA1_DDR_B" )
        , ( 0xDC04, "CIA1_TIMER_A_LO" )
        , ( 0xDC05, "CIA1_TIMER_A_HI" )
        , ( 0xDC06, "CIA1_TIMER_B_LO" )
        , ( 0xDC07, "CIA1_TIMER_B_HI" )
        , ( 0xDC08, "CIA1_TOD_TENTHS" )
        , ( 0xDC09, "CIA1_TOD_SEC" )
        , ( 0xDC0A, "CIA1_TOD_MIN" )
        , ( 0xDC0B, "CIA1_TOD_HR" )
        , ( 0xDC0C, "CIA1_SERIAL" )
        , ( 0xDC0D, "CIA1_IRQ_CONTROL" )
        , ( 0xDC0E, "CIA1_CONTROL_A" )
        , ( 0xDC0F, "CIA1_CONTROL_B" )

        -- CIA 2
        , ( 0xDD00, "CIA2_PORT_A" )
        , ( 0xDD01, "CIA2_PORT_B" )
        , ( 0xDD02, "CIA2_DDR_A" )
        , ( 0xDD03, "CIA2_DDR_B" )
        , ( 0xDD04, "CIA2_TIMER_A_LO" )
        , ( 0xDD05, "CIA2_TIMER_A_HI" )
        , ( 0xDD06, "CIA2_TIMER_B_LO" )
        , ( 0xDD07, "CIA2_TIMER_B_HI" )
        , ( 0xDD08, "CIA2_TOD_TENTHS" )
        , ( 0xDD09, "CIA2_TOD_SEC" )
        , ( 0xDD0A, "CIA2_TOD_MIN" )
        , ( 0xDD0B, "CIA2_TOD_HR" )
        , ( 0xDD0C, "CIA2_SERIAL" )
        , ( 0xDD0D, "CIA2_NMI_CONTROL" )
        , ( 0xDD0E, "CIA2_CONTROL_A" )
        , ( 0xDD0F, "CIA2_CONTROL_B" )

        -- Color RAM
        , ( 0xD800, "COLOR_RAM" )
        ]
